### ISSUE TITLE
[conversion-measurement] Feature request: Add a "report received" timestamp on the ad-tech server page

### ISSUE THREAD

**Issue by csharrison** [GoogleChromeLabs/trust-safety-demo#1]
If the ad tech server already has a bunch of reports in storage, any new ones are hard to distinguish unless you know the exact impression data you're looking for. It would be nice to include a timestamp of when the reports were received on the server to know which ones are the most recent that you might be interested in.

**Comment by maudnals** [comment]
Good idea!
Done - while I was at it I've also sorted the reports with the latest on top.
