### ISSUE TITLE
Conversion Measurement API spec and implementation query

### ISSUE THREAD

**Issue by tan31989** [GoogleChromeLabs/trust-safety-demo#3]
## Expected Behavior
While actually checking the overview of the [Conversion Measurement API](https://github.com/WICG/conversion-measurement-api#registering-attribution-sources-for-anchor-tag-navigations), the implementation talks about having an iframe/anchor tag with the following attributes:

Like:
`<a attributeon="[eTLD+1]" attributionsourceeventid=[unsigned long long] attributionexpiry=[unsigned long long] attributionreportto="[origin]">`

- `attributeon`: the eTLD+1 where attribution will be triggered for this source.
- `attributionsourceeventid`: the event-level data associated with this source. This will be limited to 64 bits of information but the value can vary for browsers that want a higher level of privacy.
- `attributionexpiry`: (optional) expiry in milliseconds for when the source should be deleted. Default is 30 days, with a maximum value of 30 days. The maximum expiry can also vary between browsers.
- `attributionreportto`: (optional) the desired endpoint that the attribution report for this source should go to. Default is the top level origin of the page.

## Actual Behavior
While the trust safety demo with conversion measurement API looks like this (sample):

`<a id="ad" href="http://127.0.0.1:8082/shoes07" conversiondestination="http://127.0.0.1:8082" impressiondata="881267" reportingorigin="http://127.0.0.1:3000" impressionexpiry="864000000" target="_parent"><img width="180" src="/shoes07.png" alt="shoes 07"></a>`

## Clarification needed:
Could someone provide more details on why would the API Explainer is talking about the attributes like `attributeon`, `attributionsourceeventid` and so on, while the actual demo code shows attributes like: `reportingorigin`, `conversiondestination` and so on?

**Comment by maudnals** [comment]
Hi @tan31989, thanks for opening this.

The reason for this difference is the following: the specification has recently [changed](https://github.com/WICG/conversion-measurement-api/blob/master/CHANGES.md#json-report-format-and-apiattribute-names) (see **JSON Report format and API/attribute names**), but in Chrome the browser codebase hasn't yet been updated to match the new specification.
When the new implementation becomes available in Chrome, the demo will be updated.

Until then: 
- The demo works as expected, so this shouldn't be a blocker for you to try out the API.
- The best place to read up about the API as it works now is [this article](https://web.dev/conversion-measurement/).

Let us know if you have any more questions!

**Comment by tan31989** [comment]
Thanks, @maudnals for the update on this.

It makes sense on the current Chrome browser codebase hasn't yet adopted it. I was confused about seeing different specs. I missed seeing the changelog. Appreciate the pointers. Closing this Issue as of now.
